name: cli
description: Command-line interface for File Encryptor.
version: 1.0.0
resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  file_encryptor_core: any
  path: ^1.9.0
  args: ^2.5.0
  flutter:
    sdk: flutter
  file_picker: ^13.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
